/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ImageType = IDL.Variant({
  'mixedMedia' : IDL.Null,
  'classicPainting' : IDL.Null,
  'textToImage' : IDL.Null,
  'imageToImage' : IDL.Null,
  'photo' : IDL.Null,
  'sketch' : IDL.Null,
});
export const Time = IDL.Int;
export const Prompt = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Text,
  'imageType' : ImageType,
  'timestamp' : Time,
  'prompt' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ImageFormData = IDL.Record({
  'creator' : IDL.Text,
  'imageType' : ImageType,
  'published' : IDL.Bool,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'blobs' : IDL.Vec(ExternalBlob),
  'prompt' : IDL.Text,
});
export const Image = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Text,
  'imageType' : ImageType,
  'views' : IDL.Nat,
  'published' : IDL.Bool,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'timestamp' : Time,
  'blobs' : IDL.Vec(ExternalBlob),
  'prompt' : IDL.Text,
  'downloads' : IDL.Nat,
});
export const PromptFormData = IDL.Record({
  'creator' : IDL.Text,
  'imageType' : ImageType,
  'prompt' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completePrompt' : IDL.Func([IDL.Text], [Prompt], []),
  'createImage' : IDL.Func([IDL.Text, ImageFormData], [Image], []),
  'createPrompt' : IDL.Func([IDL.Text, PromptFormData], [Prompt], []),
  'deleteImage' : IDL.Func([IDL.Text], [], []),
  'deletePrompt' : IDL.Func([IDL.Text], [], []),
  'getActivePrompts' : IDL.Func([], [IDL.Vec(Prompt)], ['query']),
  'getAdminContentStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'typeStats' : IDL.Record({
            'created' : IDL.Record({
              'mixedMedia' : IDL.Nat,
              'classicPainting' : IDL.Nat,
              'textToImage' : IDL.Nat,
              'imageToImage' : IDL.Nat,
              'photo' : IDL.Nat,
              'sketch' : IDL.Nat,
            }),
            'published' : IDL.Record({
              'mixedMedia' : IDL.Nat,
              'classicPainting' : IDL.Nat,
              'textToImage' : IDL.Nat,
              'imageToImage' : IDL.Nat,
              'photo' : IDL.Nat,
              'sketch' : IDL.Nat,
            }),
          }),
          'promptStats' : IDL.Record({ 'active' : IDL.Nat, 'used' : IDL.Nat }),
          'limitStats' : IDL.Record({
            'dailyLimitReached' : IDL.Bool,
            'dailyPromptCapReached' : IDL.Bool,
            'dailyUploadCapReached' : IDL.Bool,
          }),
          'imageStats' : IDL.Record({
            'created' : IDL.Nat,
            'published' : IDL.Nat,
          }),
        }),
      ],
      [],
    ),
  'getAllImageTags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getBackendBackup' : IDL.Func(
      [],
      [
        IDL.Record({
          'prompts' : IDL.Record({
            'active' : IDL.Vec(Prompt),
            'used' : IDL.Vec(Prompt),
          }),
          'images' : IDL.Record({
            'created' : IDL.Vec(Image),
            'published' : IDL.Vec(Image),
          }),
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCreatedImageCountByType' : IDL.Func(
      [],
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      ['query'],
    ),
  'getCreatedImages' : IDL.Func([], [IDL.Vec(Image)], ['query']),
  'getCreatedImagesByType' : IDL.Func([ImageType], [IDL.Vec(Image)], ['query']),
  'getDailyImageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getDailyLimitReached' : IDL.Func([], [IDL.Bool], ['query']),
  'getDailyPromptCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getDailyUploadLimitInfo' : IDL.Func(
      [],
      [IDL.Nat, IDL.Nat, IDL.Bool],
      ['query'],
    ),
  'getImage' : IDL.Func([IDL.Text], [IDL.Opt(Image)], ['query']),
  'getImagesByPrompt' : IDL.Func([IDL.Text], [IDL.Vec(Image)], ['query']),
  'getImagesByTag' : IDL.Func([IDL.Text], [IDL.Vec(Image)], ['query']),
  'getImagesCount' : IDL.Func([IDL.Bool], [IDL.Nat], ['query']),
  'getPrompt' : IDL.Func([IDL.Text], [IDL.Opt(Prompt)], ['query']),
  'getPromptLimitInfo' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Bool], ['query']),
  'getPublishedImage' : IDL.Func([IDL.Text], [IDL.Opt(Image)], ['query']),
  'getPublishedImageCountByType' : IDL.Func(
      [],
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      ['query'],
    ),
  'getPublishedImages' : IDL.Func([], [IDL.Vec(Image)], ['query']),
  'getPublishedImagesByType' : IDL.Func(
      [ImageType],
      [IDL.Vec(Image)],
      ['query'],
    ),
  'getUsedPrompt' : IDL.Func([IDL.Text], [IDL.Opt(Prompt)], ['query']),
  'getUsedPrompts' : IDL.Func([], [IDL.Vec(Prompt)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasDailyImageLimit' : IDL.Func([], [IDL.Bool], ['query']),
  'hasDailyPromptLimit' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchImages' : IDL.Func([IDL.Text], [IDL.Vec(Image)], ['query']),
  'unpublishImage' : IDL.Func([IDL.Text], [], []),
  'updatePublishedImage' : IDL.Func([IDL.Text, ImageFormData], [Image], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ImageType = IDL.Variant({
    'mixedMedia' : IDL.Null,
    'classicPainting' : IDL.Null,
    'textToImage' : IDL.Null,
    'imageToImage' : IDL.Null,
    'photo' : IDL.Null,
    'sketch' : IDL.Null,
  });
  const Time = IDL.Int;
  const Prompt = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Text,
    'imageType' : ImageType,
    'timestamp' : Time,
    'prompt' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ImageFormData = IDL.Record({
    'creator' : IDL.Text,
    'imageType' : ImageType,
    'published' : IDL.Bool,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'blobs' : IDL.Vec(ExternalBlob),
    'prompt' : IDL.Text,
  });
  const Image = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Text,
    'imageType' : ImageType,
    'views' : IDL.Nat,
    'published' : IDL.Bool,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'timestamp' : Time,
    'blobs' : IDL.Vec(ExternalBlob),
    'prompt' : IDL.Text,
    'downloads' : IDL.Nat,
  });
  const PromptFormData = IDL.Record({
    'creator' : IDL.Text,
    'imageType' : ImageType,
    'prompt' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'createdAt' : Time });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completePrompt' : IDL.Func([IDL.Text], [Prompt], []),
    'createImage' : IDL.Func([IDL.Text, ImageFormData], [Image], []),
    'createPrompt' : IDL.Func([IDL.Text, PromptFormData], [Prompt], []),
    'deleteImage' : IDL.Func([IDL.Text], [], []),
    'deletePrompt' : IDL.Func([IDL.Text], [], []),
    'getActivePrompts' : IDL.Func([], [IDL.Vec(Prompt)], ['query']),
    'getAdminContentStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'typeStats' : IDL.Record({
              'created' : IDL.Record({
                'mixedMedia' : IDL.Nat,
                'classicPainting' : IDL.Nat,
                'textToImage' : IDL.Nat,
                'imageToImage' : IDL.Nat,
                'photo' : IDL.Nat,
                'sketch' : IDL.Nat,
              }),
              'published' : IDL.Record({
                'mixedMedia' : IDL.Nat,
                'classicPainting' : IDL.Nat,
                'textToImage' : IDL.Nat,
                'imageToImage' : IDL.Nat,
                'photo' : IDL.Nat,
                'sketch' : IDL.Nat,
              }),
            }),
            'promptStats' : IDL.Record({
              'active' : IDL.Nat,
              'used' : IDL.Nat,
            }),
            'limitStats' : IDL.Record({
              'dailyLimitReached' : IDL.Bool,
              'dailyPromptCapReached' : IDL.Bool,
              'dailyUploadCapReached' : IDL.Bool,
            }),
            'imageStats' : IDL.Record({
              'created' : IDL.Nat,
              'published' : IDL.Nat,
            }),
          }),
        ],
        [],
      ),
    'getAllImageTags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getBackendBackup' : IDL.Func(
        [],
        [
          IDL.Record({
            'prompts' : IDL.Record({
              'active' : IDL.Vec(Prompt),
              'used' : IDL.Vec(Prompt),
            }),
            'images' : IDL.Record({
              'created' : IDL.Vec(Image),
              'published' : IDL.Vec(Image),
            }),
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCreatedImageCountByType' : IDL.Func(
        [],
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'getCreatedImages' : IDL.Func([], [IDL.Vec(Image)], ['query']),
    'getCreatedImagesByType' : IDL.Func(
        [ImageType],
        [IDL.Vec(Image)],
        ['query'],
      ),
    'getDailyImageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getDailyLimitReached' : IDL.Func([], [IDL.Bool], ['query']),
    'getDailyPromptCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getDailyUploadLimitInfo' : IDL.Func(
        [],
        [IDL.Nat, IDL.Nat, IDL.Bool],
        ['query'],
      ),
    'getImage' : IDL.Func([IDL.Text], [IDL.Opt(Image)], ['query']),
    'getImagesByPrompt' : IDL.Func([IDL.Text], [IDL.Vec(Image)], ['query']),
    'getImagesByTag' : IDL.Func([IDL.Text], [IDL.Vec(Image)], ['query']),
    'getImagesCount' : IDL.Func([IDL.Bool], [IDL.Nat], ['query']),
    'getPrompt' : IDL.Func([IDL.Text], [IDL.Opt(Prompt)], ['query']),
    'getPromptLimitInfo' : IDL.Func(
        [],
        [IDL.Nat, IDL.Nat, IDL.Bool],
        ['query'],
      ),
    'getPublishedImage' : IDL.Func([IDL.Text], [IDL.Opt(Image)], ['query']),
    'getPublishedImageCountByType' : IDL.Func(
        [],
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'getPublishedImages' : IDL.Func([], [IDL.Vec(Image)], ['query']),
    'getPublishedImagesByType' : IDL.Func(
        [ImageType],
        [IDL.Vec(Image)],
        ['query'],
      ),
    'getUsedPrompt' : IDL.Func([IDL.Text], [IDL.Opt(Prompt)], ['query']),
    'getUsedPrompts' : IDL.Func([], [IDL.Vec(Prompt)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasDailyImageLimit' : IDL.Func([], [IDL.Bool], ['query']),
    'hasDailyPromptLimit' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchImages' : IDL.Func([IDL.Text], [IDL.Vec(Image)], ['query']),
    'unpublishImage' : IDL.Func([IDL.Text], [], []),
    'updatePublishedImage' : IDL.Func([IDL.Text, ImageFormData], [Image], []),
  });
};

export const init = ({ IDL }) => { return []; };