/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface ImageFormData {
    creator: string;
    imageType: ImageType;
    published: boolean;
    tags: Array<string>;
    description: string;
    blobs: Array<ExternalBlob>;
    prompt: string;
}
export interface PromptFormData {
    creator: string;
    imageType: ImageType;
    prompt: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Image {
    id: string;
    creator: string;
    imageType: ImageType;
    views: bigint;
    published: boolean;
    tags: Array<string>;
    description: string;
    timestamp: Time;
    blobs: Array<ExternalBlob>;
    prompt: string;
    downloads: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Prompt {
    id: string;
    creator: string;
    imageType: ImageType;
    timestamp: Time;
    prompt: string;
}
export interface UserProfile {
    name: string;
    createdAt: Time;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ImageType {
    mixedMedia = "mixedMedia",
    classicPainting = "classicPainting",
    textToImage = "textToImage",
    imageToImage = "imageToImage",
    photo = "photo",
    sketch = "sketch"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completePrompt(promptId: string): Promise<Prompt>;
    createImage(imageId: string, form: ImageFormData): Promise<Image>;
    createPrompt(promptId: string, form: PromptFormData): Promise<Prompt>;
    deleteImage(imageId: string): Promise<void>;
    deletePrompt(promptId: string): Promise<void>;
    getActivePrompts(): Promise<Array<Prompt>>;
    getAdminContentStats(): Promise<{
        typeStats: {
            created: {
                mixedMedia: bigint;
                classicPainting: bigint;
                textToImage: bigint;
                imageToImage: bigint;
                photo: bigint;
                sketch: bigint;
            };
            published: {
                mixedMedia: bigint;
                classicPainting: bigint;
                textToImage: bigint;
                imageToImage: bigint;
                photo: bigint;
                sketch: bigint;
            };
        };
        promptStats: {
            active: bigint;
            used: bigint;
        };
        limitStats: {
            dailyLimitReached: boolean;
            dailyPromptCapReached: boolean;
            dailyUploadCapReached: boolean;
        };
        imageStats: {
            created: bigint;
            published: bigint;
        };
    }>;
    getAllImageTags(): Promise<Array<string>>;
    getBackendBackup(): Promise<{
        prompts: {
            active: Array<Prompt>;
            used: Array<Prompt>;
        };
        images: {
            created: Array<Image>;
            published: Array<Image>;
        };
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCreatedImageCountByType(): Promise<[bigint, bigint, bigint, bigint, bigint, bigint]>;
    getCreatedImages(): Promise<Array<Image>>;
    getCreatedImagesByType(imageType: ImageType): Promise<Array<Image>>;
    getDailyImageCount(): Promise<bigint>;
    getDailyLimitReached(): Promise<boolean>;
    getDailyPromptCount(): Promise<bigint>;
    getDailyUploadLimitInfo(): Promise<[bigint, bigint, boolean]>;
    getImage(imageId: string): Promise<Image | null>;
    getImagesByPrompt(promptSubstring: string): Promise<Array<Image>>;
    getImagesByTag(tag: string): Promise<Array<Image>>;
    getImagesCount(isPublished: boolean): Promise<bigint>;
    getPrompt(promptId: string): Promise<Prompt | null>;
    getPromptLimitInfo(): Promise<[bigint, bigint, boolean]>;
    getPublishedImage(imageId: string): Promise<Image | null>;
    getPublishedImageCountByType(): Promise<[bigint, bigint, bigint, bigint, bigint, bigint]>;
    getPublishedImages(): Promise<Array<Image>>;
    getPublishedImagesByType(imageType: ImageType): Promise<Array<Image>>;
    getUsedPrompt(promptId: string): Promise<Prompt | null>;
    getUsedPrompts(): Promise<Array<Prompt>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasDailyImageLimit(): Promise<boolean>;
    hasDailyPromptLimit(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchImages(searchTerm: string): Promise<Array<Image>>;
    unpublishImage(imageId: string): Promise<void>;
    updatePublishedImage(imageId: string, form: ImageFormData): Promise<Image>;
}
import type { ExternalBlob as _ExternalBlob, Image as _Image, ImageFormData as _ImageFormData, ImageType as _ImageType, Prompt as _Prompt, PromptFormData as _PromptFormData, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completePrompt(arg0: string): Promise<Prompt> {
        if (this.processError) {
            try {
                const result = await this.actor.completePrompt(arg0);
                return from_candid_Prompt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completePrompt(arg0);
            return from_candid_Prompt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createImage(arg0: string, arg1: ImageFormData): Promise<Image> {
        if (this.processError) {
            try {
                const result = await this.actor.createImage(arg0, await to_candid_ImageFormData_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Image_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createImage(arg0, await to_candid_ImageFormData_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Image_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPrompt(arg0: string, arg1: PromptFormData): Promise<Prompt> {
        if (this.processError) {
            try {
                const result = await this.actor.createPrompt(arg0, to_candid_PromptFormData_n24(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Prompt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPrompt(arg0, to_candid_PromptFormData_n24(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Prompt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteImage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteImage(arg0);
            return result;
        }
    }
    async deletePrompt(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePrompt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePrompt(arg0);
            return result;
        }
    }
    async getActivePrompts(): Promise<Array<Prompt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivePrompts();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivePrompts();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminContentStats(): Promise<{
        typeStats: {
            created: {
                mixedMedia: bigint;
                classicPainting: bigint;
                textToImage: bigint;
                imageToImage: bigint;
                photo: bigint;
                sketch: bigint;
            };
            published: {
                mixedMedia: bigint;
                classicPainting: bigint;
                textToImage: bigint;
                imageToImage: bigint;
                photo: bigint;
                sketch: bigint;
            };
        };
        promptStats: {
            active: bigint;
            used: bigint;
        };
        limitStats: {
            dailyLimitReached: boolean;
            dailyPromptCapReached: boolean;
            dailyUploadCapReached: boolean;
        };
        imageStats: {
            created: bigint;
            published: bigint;
        };
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminContentStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminContentStats();
            return result;
        }
    }
    async getAllImageTags(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllImageTags();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllImageTags();
            return result;
        }
    }
    async getBackendBackup(): Promise<{
        prompts: {
            active: Array<Prompt>;
            used: Array<Prompt>;
        };
        images: {
            created: Array<Image>;
            published: Array<Image>;
        };
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getBackendBackup();
                return from_candid_record_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBackendBackup();
            return from_candid_record_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreatedImageCountByType(): Promise<[bigint, bigint, bigint, bigint, bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreatedImageCountByType();
                return [
                    result[0],
                    result[1],
                    result[2],
                    result[3],
                    result[4],
                    result[5]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreatedImageCountByType();
            return [
                result[0],
                result[1],
                result[2],
                result[3],
                result[4],
                result[5]
            ];
        }
    }
    async getCreatedImages(): Promise<Array<Image>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreatedImages();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreatedImages();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreatedImagesByType(arg0: ImageType): Promise<Array<Image>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreatedImagesByType(to_candid_ImageType_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreatedImagesByType(to_candid_ImageType_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyImageCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyImageCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyImageCount();
            return result;
        }
    }
    async getDailyLimitReached(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyLimitReached();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyLimitReached();
            return result;
        }
    }
    async getDailyPromptCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyPromptCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyPromptCount();
            return result;
        }
    }
    async getDailyUploadLimitInfo(): Promise<[bigint, bigint, boolean]> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyUploadLimitInfo();
                return [
                    result[0],
                    result[1],
                    result[2]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyUploadLimitInfo();
            return [
                result[0],
                result[1],
                result[2]
            ];
        }
    }
    async getImage(arg0: string): Promise<Image | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getImage(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImage(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImagesByPrompt(arg0: string): Promise<Array<Image>> {
        if (this.processError) {
            try {
                const result = await this.actor.getImagesByPrompt(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImagesByPrompt(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImagesByTag(arg0: string): Promise<Array<Image>> {
        if (this.processError) {
            try {
                const result = await this.actor.getImagesByTag(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImagesByTag(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImagesCount(arg0: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getImagesCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImagesCount(arg0);
            return result;
        }
    }
    async getPrompt(arg0: string): Promise<Prompt | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrompt(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrompt(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPromptLimitInfo(): Promise<[bigint, bigint, boolean]> {
        if (this.processError) {
            try {
                const result = await this.actor.getPromptLimitInfo();
                return [
                    result[0],
                    result[1],
                    result[2]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPromptLimitInfo();
            return [
                result[0],
                result[1],
                result[2]
            ];
        }
    }
    async getPublishedImage(arg0: string): Promise<Image | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedImage(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedImage(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedImageCountByType(): Promise<[bigint, bigint, bigint, bigint, bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedImageCountByType();
                return [
                    result[0],
                    result[1],
                    result[2],
                    result[3],
                    result[4],
                    result[5]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedImageCountByType();
            return [
                result[0],
                result[1],
                result[2],
                result[3],
                result[4],
                result[5]
            ];
        }
    }
    async getPublishedImages(): Promise<Array<Image>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedImages();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedImages();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedImagesByType(arg0: ImageType): Promise<Array<Image>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedImagesByType(to_candid_ImageType_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedImagesByType(to_candid_ImageType_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsedPrompt(arg0: string): Promise<Prompt | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsedPrompt(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsedPrompt(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsedPrompts(): Promise<Array<Prompt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsedPrompts();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsedPrompts();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasDailyImageLimit(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasDailyImageLimit();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasDailyImageLimit();
            return result;
        }
    }
    async hasDailyPromptLimit(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasDailyPromptLimit();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasDailyPromptLimit();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchImages(arg0: string): Promise<Array<Image>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchImages(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchImages(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async unpublishImage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unpublishImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpublishImage(arg0);
            return result;
        }
    }
    async updatePublishedImage(arg0: string, arg1: ImageFormData): Promise<Image> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePublishedImage(arg0, await to_candid_ImageFormData_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Image_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePublishedImage(arg0, await to_candid_ImageFormData_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Image_n20(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ImageType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImageType): ImageType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function from_candid_Image_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Image): Promise<Image> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Prompt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Prompt): Prompt {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Image]): Promise<Image | null> {
    return value.length === 0 ? null : await from_candid_Image_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Prompt]): Prompt | null {
    return value.length === 0 ? null : from_candid_Prompt_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    creator: string;
    imageType: _ImageType;
    timestamp: _Time;
    prompt: string;
}): {
    id: string;
    creator: string;
    imageType: ImageType;
    timestamp: Time;
    prompt: string;
} {
    return {
        id: value.id,
        creator: value.creator,
        imageType: from_candid_ImageType_n12(_uploadFile, _downloadFile, value.imageType),
        timestamp: value.timestamp,
        prompt: value.prompt
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    creator: string;
    imageType: _ImageType;
    views: bigint;
    published: boolean;
    tags: Array<string>;
    description: string;
    timestamp: _Time;
    blobs: Array<_ExternalBlob>;
    prompt: string;
    downloads: bigint;
}): Promise<{
    id: string;
    creator: string;
    imageType: ImageType;
    views: bigint;
    published: boolean;
    tags: Array<string>;
    description: string;
    timestamp: Time;
    blobs: Array<ExternalBlob>;
    prompt: string;
    downloads: bigint;
}> {
    return {
        id: value.id,
        creator: value.creator,
        imageType: from_candid_ImageType_n12(_uploadFile, _downloadFile, value.imageType),
        views: value.views,
        published: value.published,
        tags: value.tags,
        description: value.description,
        timestamp: value.timestamp,
        blobs: await from_candid_vec_n22(_uploadFile, _downloadFile, value.blobs),
        prompt: value.prompt,
        downloads: value.downloads
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    prompts: {
        active: Array<_Prompt>;
        used: Array<_Prompt>;
    };
    images: {
        created: Array<_Image>;
        published: Array<_Image>;
    };
}): Promise<{
    prompts: {
        active: Array<Prompt>;
        used: Array<Prompt>;
    };
    images: {
        created: Array<Image>;
        published: Array<Image>;
    };
}> {
    return {
        prompts: from_candid_record_n28(_uploadFile, _downloadFile, value.prompts),
        images: await from_candid_record_n29(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: Array<_Prompt>;
    used: Array<_Prompt>;
}): {
    active: Array<Prompt>;
    used: Array<Prompt>;
} {
    return {
        active: from_candid_vec_n26(_uploadFile, _downloadFile, value.active),
        used: from_candid_vec_n26(_uploadFile, _downloadFile, value.used)
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    created: Array<_Image>;
    published: Array<_Image>;
}): Promise<{
    created: Array<Image>;
    published: Array<Image>;
}> {
    return {
        created: await from_candid_vec_n30(_uploadFile, _downloadFile, value.created),
        published: await from_candid_vec_n30(_uploadFile, _downloadFile, value.published)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mixedMedia: null;
} | {
    classicPainting: null;
} | {
    textToImage: null;
} | {
    imageToImage: null;
} | {
    photo: null;
} | {
    sketch: null;
}): ImageType {
    return "mixedMedia" in value ? ImageType.mixedMedia : "classicPainting" in value ? ImageType.classicPainting : "textToImage" in value ? ImageType.textToImage : "imageToImage" in value ? ImageType.imageToImage : "photo" in value ? ImageType.photo : "sketch" in value ? ImageType.sketch : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Prompt>): Array<Prompt> {
    return value.map((x)=>from_candid_Prompt_n10(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Image>): Promise<Array<Image>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Image_n20(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_ImageFormData_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImageFormData): Promise<_ImageFormData> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_ImageType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImageType): _ImageType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_PromptFormData_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PromptFormData): _PromptFormData {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creator: string;
    imageType: ImageType;
    published: boolean;
    tags: Array<string>;
    description: string;
    blobs: Array<ExternalBlob>;
    prompt: string;
}): Promise<{
    creator: string;
    imageType: _ImageType;
    published: boolean;
    tags: Array<string>;
    description: string;
    blobs: Array<_ExternalBlob>;
    prompt: string;
}> {
    return {
        creator: value.creator,
        imageType: to_candid_ImageType_n16(_uploadFile, _downloadFile, value.imageType),
        published: value.published,
        tags: value.tags,
        description: value.description,
        blobs: await to_candid_vec_n18(_uploadFile, _downloadFile, value.blobs),
        prompt: value.prompt
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creator: string;
    imageType: ImageType;
    prompt: string;
}): {
    creator: string;
    imageType: _ImageType;
    prompt: string;
} {
    return {
        creator: value.creator,
        imageType: to_candid_ImageType_n16(_uploadFile, _downloadFile, value.imageType),
        prompt: value.prompt
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImageType): {
    mixedMedia: null;
} | {
    classicPainting: null;
} | {
    textToImage: null;
} | {
    imageToImage: null;
} | {
    photo: null;
} | {
    sketch: null;
} {
    return value == ImageType.mixedMedia ? {
        mixedMedia: null
    } : value == ImageType.classicPainting ? {
        classicPainting: null
    } : value == ImageType.textToImage ? {
        textToImage: null
    } : value == ImageType.imageToImage ? {
        imageToImage: null
    } : value == ImageType.photo ? {
        photo: null
    } : value == ImageType.sketch ? {
        sketch: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n19(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
