/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Image {
  'id' : string,
  'creator' : string,
  'imageType' : ImageType,
  'views' : bigint,
  'published' : boolean,
  'tags' : Array<string>,
  'description' : string,
  'timestamp' : Time,
  'blobs' : Array<ExternalBlob>,
  'prompt' : string,
  'downloads' : bigint,
}
export interface ImageFormData {
  'creator' : string,
  'imageType' : ImageType,
  'published' : boolean,
  'tags' : Array<string>,
  'description' : string,
  'blobs' : Array<ExternalBlob>,
  'prompt' : string,
}
export type ImageType = { 'mixedMedia' : null } |
  { 'classicPainting' : null } |
  { 'textToImage' : null } |
  { 'imageToImage' : null } |
  { 'photo' : null } |
  { 'sketch' : null };
export interface Prompt {
  'id' : string,
  'creator' : string,
  'imageType' : ImageType,
  'timestamp' : Time,
  'prompt' : string,
}
export interface PromptFormData {
  'creator' : string,
  'imageType' : ImageType,
  'prompt' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'createdAt' : Time }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completePrompt' : ActorMethod<[string], Prompt>,
  'createImage' : ActorMethod<[string, ImageFormData], Image>,
  'createPrompt' : ActorMethod<[string, PromptFormData], Prompt>,
  'deleteImage' : ActorMethod<[string], undefined>,
  'deletePrompt' : ActorMethod<[string], undefined>,
  'getActivePrompts' : ActorMethod<[], Array<Prompt>>,
  'getAdminContentStats' : ActorMethod<
    [],
    {
      'typeStats' : {
        'created' : {
          'mixedMedia' : bigint,
          'classicPainting' : bigint,
          'textToImage' : bigint,
          'imageToImage' : bigint,
          'photo' : bigint,
          'sketch' : bigint,
        },
        'published' : {
          'mixedMedia' : bigint,
          'classicPainting' : bigint,
          'textToImage' : bigint,
          'imageToImage' : bigint,
          'photo' : bigint,
          'sketch' : bigint,
        },
      },
      'promptStats' : { 'active' : bigint, 'used' : bigint },
      'limitStats' : {
        'dailyLimitReached' : boolean,
        'dailyPromptCapReached' : boolean,
        'dailyUploadCapReached' : boolean,
      },
      'imageStats' : { 'created' : bigint, 'published' : bigint },
    }
  >,
  'getAllImageTags' : ActorMethod<[], Array<string>>,
  'getBackendBackup' : ActorMethod<
    [],
    {
      'prompts' : { 'active' : Array<Prompt>, 'used' : Array<Prompt> },
      'images' : { 'created' : Array<Image>, 'published' : Array<Image> },
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCreatedImageCountByType' : ActorMethod<
    [],
    [bigint, bigint, bigint, bigint, bigint, bigint]
  >,
  'getCreatedImages' : ActorMethod<[], Array<Image>>,
  'getCreatedImagesByType' : ActorMethod<[ImageType], Array<Image>>,
  'getDailyImageCount' : ActorMethod<[], bigint>,
  'getDailyLimitReached' : ActorMethod<[], boolean>,
  'getDailyPromptCount' : ActorMethod<[], bigint>,
  'getDailyUploadLimitInfo' : ActorMethod<[], [bigint, bigint, boolean]>,
  'getImage' : ActorMethod<[string], [] | [Image]>,
  'getImagesByPrompt' : ActorMethod<[string], Array<Image>>,
  'getImagesByTag' : ActorMethod<[string], Array<Image>>,
  'getImagesCount' : ActorMethod<[boolean], bigint>,
  'getPrompt' : ActorMethod<[string], [] | [Prompt]>,
  'getPromptLimitInfo' : ActorMethod<[], [bigint, bigint, boolean]>,
  'getPublishedImage' : ActorMethod<[string], [] | [Image]>,
  'getPublishedImageCountByType' : ActorMethod<
    [],
    [bigint, bigint, bigint, bigint, bigint, bigint]
  >,
  'getPublishedImages' : ActorMethod<[], Array<Image>>,
  'getPublishedImagesByType' : ActorMethod<[ImageType], Array<Image>>,
  'getUsedPrompt' : ActorMethod<[string], [] | [Prompt]>,
  'getUsedPrompts' : ActorMethod<[], Array<Prompt>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasDailyImageLimit' : ActorMethod<[], boolean>,
  'hasDailyPromptLimit' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchImages' : ActorMethod<[string], Array<Image>>,
  'unpublishImage' : ActorMethod<[string], undefined>,
  'updatePublishedImage' : ActorMethod<[string, ImageFormData], Image>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];